# -*- coding: utf-8 -*-
"""image_classification(mnist)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bfLDSH1vWcZ_SMrNuQsXNF0JoBAKg3jv
"""

!pip install autokeras

import numpy as np
from tensorflow.keras.datasets import mnist
import autokeras as ak

(X_train, y_train), (X_test, y_test) = mnist.load_data()
print(X_train.shape)  # (60000, 28, 28)
print(y_train.shape)  # (60000,)
print(y_train[:10])

X_train = X_train / 255.0
X_test = X_test / 255.0

X_train[0]

# Initialize the image classifier.
clf = ak.ImageClassifier(overwrite=True, max_trials=1)
# Feed the image classifier with training data.
clf.fit(X_train, y_train, epochs=2)
# Evaluate the best model with testing data.
print(clf.evaluate(X_test, y_test))

from keras.utils.vis_utils import plot_model

plot_model(clf.export_model())

# Predict with the best model.
y_pred = clf.predict(X_test)

# Visualize the prediction result
from matplotlib import pyplot as plt

plt.figure(figsize=(16,6))
for i in range(30):
    plt.subplot(3,10,i+1)
    plt.imshow(X_test[i].reshape(28,28), cmap='gray', interpolation='none')
    plt.title("Label:{}\n Pred:{}".format(y_test[i], y_pred[i][0]))
    plt.axis('off')

import dill as pickle   # Pure pickle fails here
import os

with open('model_autokeras.h5', 'wb') as f:
    pickle.dump(clf, f, pickle.HIGHEST_PROTOCOL)
os.system("tar cvf - model_autokeras.h5 image_classifier | gzip > ic.tar.gz")